### ISSUE TITLE
缺少dataset文件

### ISSUE THREAD

**Issue by slnxyr** [bellymonster/Weighted-Soft-Label-Distillation#1]
由于没有dataset，我尝试复现了一下，但是存在一些细节上的不一致，请问能提供一下dataset文件吗？

**Comment by bellymonster** [comment]
Hello, we use standard ImageNet as out dataset. By default, we pack the ImageNet data as the lmdb file for faster IO. We also provide a way to read the original images by setting the config. In our latest version, you can choose generate lmdb files according to README，or you can use the original ImageNet images to run the code. We have tested both loading methods and their final accuracy is similar (0.1% difference, which is a reasonable fluctuation).
