### ISSUE TITLE
Minor questions on Eq.(2)

### ISSUE THREAD

**Issue by HolmesShuan** [bellymonster/Weighted-Soft-Label-Distillation#3]
Hi, I have read your excellent work several times. The bias-variance idea is very interesting! 

However, due to my poor knowledge of "bias/variance" theorem, I found the variance term in Equation (2) hard to understand. E.g.,
How to prove that 
<a href="https://www.codecogs.com/eqnedit.php?latex=\mathbb{E}_D[\mathbb{E}_\mathrm{x}[\mathrm{y}\log\frac{\overline{\mathrm{y}}_{ce}}{\hat{y}_{ce}}]]]=\mathbb{E}_D[D_{KL}(\overline{\mathrm{y}}_{ce},\hat{\mathrm{y}}_{ce})]?" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\mathbb{E}_D[\mathbb{E}_\mathrm{x}[\mathrm{y}\log\frac{\overline{\mathrm{y}}_{ce}}{\hat{y}_{ce}}]]]=\mathbb{E}_D[D_{KL}(\overline{\mathrm{y}}_{ce},\hat{\mathrm{y}}_{ce})]?" title="\mathbb{E}_D[\mathbb{E}_\mathrm{x}[\mathrm{y}\log\frac{\overline{\mathrm{y}}_{ce}}{\hat{y}_{ce}}]]]=\mathbb{E}_D[D_{KL}(\overline{\mathrm{y}}_{ce},\hat{\mathrm{y}}_{ce})]?" /></a>

I have referred to Heskes's paper and it seems that the derivation relies on the normalization constant **Z** in Equation (1). It is easy to prove that 
<a href="https://www.codecogs.com/eqnedit.php?latex=\frac{\log&space;\overline{\mathrm&space;y}_{ce}}{\mathbb{E}_D[\log&space;\hat{y}_{ce}]}=constant" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\frac{\log&space;\overline{\mathrm&space;y}_{ce}}{\mathbb{E}_D[\log&space;\hat{y}_{ce}]}=constant" title="\frac{\log \overline{\mathrm y}_{ce}}{\mathbb{E}_D[\log \hat{y}_{ce}]}=constant" /></a>
if  **Z** in Equation (1) is a constant value. But I still did not find the relationship between this term and Equation (2). 

Could you please kindly provide the detailed derivations of the variance term in Equation (2)? Thanks in advance.

**Comment by lsongx** [comment]
Hi @HolmesShuan , thanks for your question!
The reason is that E(y) and E(\bar{y}) are all equals to 1. Please refer to the equation above Eqn 4 from Heskes's paper: an extra \bar{p}(y) in the second row.
This follows the definition used in Eqn 2 from Heskes's paper. In their paper, it is defined \int dy a(y) = 1. (constraints in Eqn 2) 
In our notations, y becomes x and a() becomes y=t(). We originally kept all notations the same as Heskes's paper, but a reviewer thinks the notations are not appropriate thus we changed all notations. 
Sorry for the confusion! Please let me know if there are any further questions.

**Comment by HolmesShuan** [comment]
Hi @LcDog , thanks for your quick reply!

I have double-checked the derivation of Heskes's paper and gradually understood the decomposition for the expected error defined on the KL Div. Unfortunately, I still did not get the idea of how `E(y) and E(\bar{y}) are all equals to 1` leads to 
<a href="https://www.codecogs.com/eqnedit.php?latex=\mathbb{E}_D[\mathbb{E}_\mathrm{x}[\mathrm{y}\log\frac{\overline{\mathrm{y}}_{ce}}{\hat{y}_{ce}}]]]=\mathbb{E}_D[D_{KL}(\overline{\mathrm{y}}_{ce},\hat{\mathrm{y}}_{ce})]?" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\mathbb{E}_D[\mathbb{E}_\mathrm{x}[\mathrm{y}\log\frac{\overline{\mathrm{y}}_{ce}}{\hat{y}_{ce}}]]]=\mathbb{E}_D[D_{KL}(\overline{\mathrm{y}}_{ce},\hat{\mathrm{y}}_{ce})]?" title="\mathbb{E}_D[\mathbb{E}_\mathrm{x}[\mathrm{y}\log\frac{\overline{\mathrm{y}}_{ce}}{\hat{y}_{ce}}]]]=\mathbb{E}_D[D_{KL}(\overline{\mathrm{y}}_{ce},\hat{\mathrm{y}}_{ce})]?" /></a>

I am really sorry for bothering you again :(

As far as I can tell,
<a href="https://www.codecogs.com/eqnedit.php?latex=\mathbb{E}_D[\mathbb{E}_x[\mathrm&space;y\log\frac{\overline{\mathrm&space;y}}{\hat{\mathrm&space;y}}]]=\mathbb{E}_D[\mathbb{E}_x[\mathrm&space;y\log\overline{\mathrm&space;y}-\mathrm&space;y\log\hat{\mathrm&space;y}]]=\mathbb{E}_x[\mathrm&space;y\log\overline{\mathrm&space;y}]-\mathbb{E}_D[\mathbb{E}_x[\mathrm&space;y\log\hat{\mathrm&space;y}]]" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\mathbb{E}_D[\mathbb{E}_x[\mathrm&space;y\log\frac{\overline{\mathrm&space;y}}{\hat{\mathrm&space;y}}]]=\mathbb{E}_D[\mathbb{E}_x[\mathrm&space;y\log\overline{\mathrm&space;y}-\mathrm&space;y\log\hat{\mathrm&space;y}]]=\mathbb{E}_x[\mathrm&space;y\log\overline{\mathrm&space;y}]-\mathbb{E}_D[\mathbb{E}_x[\mathrm&space;y\log\hat{\mathrm&space;y}]]" title="\mathbb{E}_D[\mathbb{E}_x[\mathrm y\log\frac{\overline{\mathrm y}}{\hat{\mathrm y}}]]=\mathbb{E}_D[\mathbb{E}_x[\mathrm y\log\overline{\mathrm y}-\mathrm y\log\hat{\mathrm y}]]=\mathbb{E}_x[\mathrm y\log\overline{\mathrm y}]-\mathbb{E}_D[\mathbb{E}_x[\mathrm y\log\hat{\mathrm y}]]" /></a>
I am not sure how to use `E(y) and E(\bar{y}) are all equals to 1` in the above equation. It seems that
<a href="https://www.codecogs.com/eqnedit.php?latex=\mathbb{E}_x[f(x)g(x)]\neq\mathbb{E}_x[f(x)]\mathbb{E}_x[g(x)]" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\mathbb{E}_x[f(x)g(x)]\neq\mathbb{E}_x[f(x)]\mathbb{E}_x[g(x)]" title="\mathbb{E}_x[f(x)g(x)]\neq\mathbb{E}_x[f(x)]\mathbb{E}_x[g(x)]" /></a>

Many thanks!

**Comment by lsongx** [comment]
No problem! You are very welcome to ask anything~

No need to decompose the two terms. We first have
<a href="https://www.codecogs.com/eqnedit.php?latex=\mathbb{E}_D[\log\frac{\overline{\mathrm&space;y}}{\hat{\mathrm&space;y}}]=\log&space;Z" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\mathbb{E}_D[\log\frac{\overline{\mathrm&space;y}}{\hat{\mathrm&space;y}}]=\log&space;Z" title="\mathbb{E}_D[\log\frac{\overline{\mathrm y}}{\hat{\mathrm y}}]=\log Z" /></a>
then
<a href="https://www.codecogs.com/eqnedit.php?latex=\int&space;y\mathbb{E}_D[\log\frac{\overline{\mathrm&space;y}}{\hat{\mathrm&space;y}}]&space;\mathrm{d}x=\int&space;y\log&space;Z&space;\mathrm{d}x" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\int&space;y\mathbb{E}_D[\log\frac{\overline{\mathrm&space;y}}{\hat{\mathrm&space;y}}]&space;\mathrm{d}x=\int&space;y\log&space;Z&space;\mathrm{d}x" title="\int y\mathbb{E}_D[\log\frac{\overline{\mathrm y}}{\hat{\mathrm y}}] \mathrm{d}x=\int y\log Z \mathrm{d}x" /></a>
so
<a href="https://www.codecogs.com/eqnedit.php?latex=\mathbb{E}_D[\int&space;y\log\frac{\overline{\mathrm&space;y}}{\hat{\mathrm&space;y}}&space;\mathrm{d}x]=\int&space;y\log&space;Z&space;\mathrm{d}x" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\mathbb{E}_D[\int&space;y\log\frac{\overline{\mathrm&space;y}}{\hat{\mathrm&space;y}}&space;\mathrm{d}x]=\int&space;y\log&space;Z&space;\mathrm{d}x" title="\mathbb{E}_D[\int y\log\frac{\overline{\mathrm y}}{\hat{\mathrm y}} \mathrm{d}x]=\int y\log Z \mathrm{d}x" /></a>
similar we have
<a href="https://www.codecogs.com/eqnedit.php?latex=\mathbb{E}_D[\int&space;\bar{y}\log\frac{\overline{\mathrm&space;y}}{\hat{\mathrm&space;y}}&space;\mathrm{d}x]=\int&space;\bar{y}\log&space;Z&space;\mathrm{d}x" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\mathbb{E}_D[\int&space;\bar{y}\log\frac{\overline{\mathrm&space;y}}{\hat{\mathrm&space;y}}&space;\mathrm{d}x]=\int&space;\bar{y}\log&space;Z&space;\mathrm{d}x" title="\mathbb{E}_D[\int \bar{y}\log\frac{\overline{\mathrm y}}{\hat{\mathrm y}} \mathrm{d}x]=\int \bar{y}\log Z \mathrm{d}x" /></a>

By the way, could you further explain how to get the equation in your first comment?
<a href="https://www.codecogs.com/eqnedit.php?latex=\frac{\log&space;\overline{\mathrm&space;y}_{ce}}{\mathbb{E}_D[\log&space;\hat{y}_{ce}]}=constant" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\frac{\log&space;\overline{\mathrm&space;y}_{ce}}{\mathbb{E}_D[\log&space;\hat{y}_{ce}]}=constant" title="\frac{\log \overline{\mathrm y}_{ce}}{\mathbb{E}_D[\log \hat{y}_{ce}]}=constant" /></a>
Seems like that our notations are somewhat misleading

**Comment by HolmesShuan** [comment]
Cool! The derivation is very clear!

It seems that 
<a href="https://www.codecogs.com/eqnedit.php?latex=\mathbb{E}_D[\log\frac{\overline{\mathrm&space;y}}{\hat{\mathrm&space;y}}]]=-\log\mathrm&space;Z?" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\mathbb{E}_D[\log\frac{\overline{\mathrm&space;y}}{\hat{\mathrm&space;y}}]]=-\log\mathrm&space;Z?" title="\mathbb{E}_D[\log\frac{\overline{\mathrm y}}{\hat{\mathrm y}}]]=-\log\mathrm Z?" /></a>
according to
<a href="https://www.codecogs.com/eqnedit.php?latex=\overline{\mathrm&space;y}=\frac{1}{\mathrm&space;Z}\exp(\mathbb{E}_D[\log&space;\hat{\mathrm&space;y}])" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\overline{\mathrm&space;y}=\frac{1}{\mathrm&space;Z}\exp(\mathbb{E}_D[\log&space;\hat{\mathrm&space;y}])" title="\overline{\mathrm y}=\frac{1}{\mathrm Z}\exp(\mathbb{E}_D[\log \hat{\mathrm y}])" /></a>

The notation is ok but I found `E[y]=1 and E[\overline y]=1` quite confusing, which makes me wonder is there any
<a href="https://www.codecogs.com/eqnedit.php?latex=\mathbb{E}[*]=\mathbb{E}[*]\cdot1=\mathbb{E}[*]\cdot\mathbb{E}[\mathrm&space;y]=\mathbb{E}[*]\cdot\mathbb{E}[\overline{\mathrm&space;y}]..." target="_blank"><img src="https://latex.codecogs.com/gif.latex?\mathbb{E}[*]=\mathbb{E}[*]\cdot1=\mathbb{E}[*]\cdot\mathbb{E}[\mathrm&space;y]=\mathbb{E}[*]\cdot\mathbb{E}[\overline{\mathrm&space;y}]..." title="\mathbb{E}[*]=\mathbb{E}[*]\cdot1=\mathbb{E}[*]\cdot\mathbb{E}[\mathrm y]=\mathbb{E}[*]\cdot\mathbb{E}[\overline{\mathrm y}]..." /></a>
tricks in Equation(2). :sweat_smile:





> By the way, could you further explain how to get the equation in your first comment?
> [![](https://camo.githubusercontent.com/6da5d32079669f8e964a91fb19fb9bfbb124301b6eea7a484c08d8ac617440a7/68747470733a2f2f6c617465782e636f6465636f67732e636f6d2f6769662e6c617465783f5c667261637b5c6c6f672673706163653b5c6f7665726c696e657b5c6d617468726d2673706163653b797d5f7b63657d7d7b5c6d61746862627b457d5f445b5c6c6f672673706163653b5c6861747b797d5f7b63657d5d7d3d636f6e7374616e74)](https://www.codecogs.com/eqnedit.php?latex=\frac{\log&space;\overline{\mathrm&space;y}_{ce}}{\mathbb{E}_D[\log&space;\hat{y}_{ce}]}=constant)

As for 
<a href="https://www.codecogs.com/eqnedit.php?latex=\frac{\log&space;\overline{\mathrm&space;y}_{ce}}{\mathbb{E}_D[\log&space;\hat{y}_{ce}]}=constant" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\frac{\log&space;\overline{\mathrm&space;y}_{ce}}{\mathbb{E}_D[\log&space;\hat{y}_{ce}]}=constant" title="\frac{\log \overline{\mathrm y}_{ce}}{\mathbb{E}_D[\log \hat{y}_{ce}]}=constant" /></a>
I just quoted the conclusion in the ICLR paper "The derivation of the variance term is based on the facts that $\frac{\log \overline{y}_{ce}}{\mathbb{E}_\mathcal{D}[\log \hat{y}_{ce}]}$ is a constant and ...". 

Thanks for your responses!

**Comment by lsongx** [comment]
Glad that I have addressed your concerns. 

The equation in the paper seems wrong. 
It should be <a href="https://www.codecogs.com/eqnedit.php?latex=\mathbb{E}_D[\log\frac{\overline{\mathrm&space;y}}{\hat{\mathrm&space;y}}]=\log&space;Z" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\mathbb{E}_D[\log\frac{\overline{\mathrm&space;y}}{\hat{\mathrm&space;y}}]=\log&space;Z" title="\mathbb{E}_D[\log\frac{\overline{\mathrm y}}{\hat{\mathrm y}}]=\log Z" /></a> 

Thanks for your question!
